:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

dotnet restore src\WildApricot
dotnet build src\WildApricot
echo Now, run the following to start the project: dotnet run -p src\WildApricot\WildApricot.csproj --launch-profile web.
echo.
