/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Information about Wild Apricot account
    /// </summary>
    [DataContract]
    public partial class Account : IEquatable<Account>
    {
        /// <summary>
        /// Unique account identifier.
        /// </summary>
        /// <value>Unique account identifier.</value>

        [DataMember(Name = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// The organization name.
        /// </summary>
        /// <value>The organization name.</value>

        [DataMember(Name = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Address of API call providing account details.
        /// </summary>
        /// <value>Address of API call providing account details.</value>

        [DataMember(Name = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// The primary domain name for the account.
        /// </summary>
        /// <value>The primary domain name for the account.</value>

        [DataMember(Name = "PrimaryDomainName")]
        public string PrimaryDomainName { get; set; }

        /// <summary>
        /// Collection of account-related resources.
        /// </summary>
        /// <value>Collection of account-related resources.</value>

        [DataMember(Name = "Resources")]
        public List<Resource> Resources { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>

        [DataMember(Name = "Currency")]
        public Currency Currency { get; set; }

        /// <summary>
        /// Gets or Sets Localization
        /// </summary>

        [DataMember(Name = "Localization")]
        public Localization Localization { get; set; }

        /// <summary>
        /// Gets or Sets TimeZone
        /// </summary>

        [DataMember(Name = "TimeZone")]
        public TimeZoneDescription TimeZone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Account {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  PrimaryDomainName: ").Append(PrimaryDomainName).Append("\n");
            sb.Append("  Resources: ").Append(Resources).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Localization: ").Append(Localization).Append("\n");
            sb.Append("  TimeZone: ").Append(TimeZone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((Account)obj);
        }

        /// <summary>
        /// Returns true if Account instances are equal
        /// </summary>
        /// <param name="other">Instance of Account to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Account other)
        {
            if (ReferenceEquals(null, other))
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (Id == other.Id || Id != null && Id.Equals(other.Id))
                && (Name == other.Name || Name != null && Name.Equals(other.Name))
                && (Url == other.Url || Url != null && Url.Equals(other.Url))
                && (
                    PrimaryDomainName == other.PrimaryDomainName
                    || PrimaryDomainName != null
                        && PrimaryDomainName.Equals(other.PrimaryDomainName)
                )
                && (
                    Resources == other.Resources
                    || Resources != null && Resources.SequenceEqual(other.Resources)
                )
                && (
                    Currency == other.Currency
                    || Currency != null && Currency.Equals(other.Currency)
                )
                && (
                    Localization == other.Localization
                    || Localization != null && Localization.Equals(other.Localization)
                )
                && (
                    TimeZone == other.TimeZone
                    || TimeZone != null && TimeZone.Equals(other.TimeZone)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                if (PrimaryDomainName != null)
                    hashCode = hashCode * 59 + PrimaryDomainName.GetHashCode();
                if (Resources != null)
                    hashCode = hashCode * 59 + Resources.GetHashCode();
                if (Currency != null)
                    hashCode = hashCode * 59 + Currency.GetHashCode();
                if (Localization != null)
                    hashCode = hashCode * 59 + Localization.GetHashCode();
                if (TimeZone != null)
                    hashCode = hashCode * 59 + TimeZone.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(Account left, Account right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Account left, Account right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
