/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class CustomFieldAllowedValue : IEquatable<CustomFieldAllowedValue>
    {
        /// <summary>
        /// Unique option identifier.
        /// </summary>
        /// <value>Unique option identifier.</value>
        [Required]
        [DataMember(Name = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// Human-readable text label.
        /// </summary>
        /// <value>Human-readable text label.</value>
        [Required]
        [DataMember(Name = "Label")]
        public string Label { get; set; }

        /// <summary>
        /// Price of item, when applying for membership or registering for event.
        /// </summary>
        /// <value>Price of item, when applying for membership or registering for event.</value>

        [DataMember(Name = "ExtraCost")]
        public decimal? ExtraCost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CustomFieldAllowedValue {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  ExtraCost: ").Append(ExtraCost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((CustomFieldAllowedValue)obj);
        }

        /// <summary>
        /// Returns true if CustomFieldAllowedValue instances are equal
        /// </summary>
        /// <param name="other">Instance of CustomFieldAllowedValue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomFieldAllowedValue other)
        {
            if (ReferenceEquals(null, other))
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (Id == other.Id || Id != null && Id.Equals(other.Id))
                && (Label == other.Label || Label != null && Label.Equals(other.Label))
                && (
                    ExtraCost == other.ExtraCost
                    || ExtraCost != null && ExtraCost.Equals(other.ExtraCost)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Label != null)
                    hashCode = hashCode * 59 + Label.GetHashCode();
                if (ExtraCost != null)
                    hashCode = hashCode * 59 + ExtraCost.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(CustomFieldAllowedValue left, CustomFieldAllowedValue right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CustomFieldAllowedValue left, CustomFieldAllowedValue right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
