/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Contains a collection of events or number of events or list of event identifiers, depending on passed query parameters.
    /// </summary>
    [DataContract]
    public partial class EventsResponse : IEquatable<EventsResponse>
    {
        /// <summary>
        /// List of events found.
        /// </summary>
        /// <value>List of events found.</value>

        [DataMember(Name = "Events")]
        public List<ModelEvent> Events { get; set; }

        /// <summary>
        /// List of identifiers of events found.
        /// </summary>
        /// <value>List of identifiers of events found.</value>

        [DataMember(Name = "EventIdentifiers")]
        public List<int?> EventIdentifiers { get; set; }

        /// <summary>
        /// Number of events found. Value is returned only if $count was passed in parameters.
        /// </summary>
        /// <value>Number of events found. Value is returned only if $count was passed in parameters.</value>

        [DataMember(Name = "Count")]
        public int? Count { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EventsResponse {\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  EventIdentifiers: ").Append(EventIdentifiers).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((EventsResponse)obj);
        }

        /// <summary>
        /// Returns true if EventsResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of EventsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventsResponse other)
        {
            if (ReferenceEquals(null, other))
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (Events == other.Events || Events != null && Events.SequenceEqual(other.Events))
                && (
                    EventIdentifiers == other.EventIdentifiers
                    || EventIdentifiers != null
                        && EventIdentifiers.SequenceEqual(other.EventIdentifiers)
                )
                && (Count == other.Count || Count != null && Count.Equals(other.Count));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Events != null)
                    hashCode = hashCode * 59 + Events.GetHashCode();
                if (EventIdentifiers != null)
                    hashCode = hashCode * 59 + EventIdentifiers.GetHashCode();
                if (Count != null)
                    hashCode = hashCode * 59 + Count.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(EventsResponse left, EventsResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EventsResponse left, EventsResponse right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
