/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class EventSession : IEquatable<EventSession>
    {
        /// <summary>
        /// Unique event session identifier.
        /// </summary>
        /// <value>Unique event session identifier.</value>
        [Required]
        [DataMember(Name = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// Session title
        /// </summary>
        /// <value>Session title</value>

        [DataMember(Name = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// Date and optionally time when event session starts.
        /// </summary>
        /// <value>Date and optionally time when event session starts.</value>
        [Required]
        [DataMember(Name = "StartDate")]
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// Indicates whether start time was explicitly specified in StartDate. A value of false means StartDate contains date only.
        /// </summary>
        /// <value>Indicates whether start time was explicitly specified in StartDate. A value of false means StartDate contains date only.</value>

        [DataMember(Name = "StartTimeSpecified")]
        public bool? StartTimeSpecified { get; set; }

        /// <summary>
        /// Date and optionally time when event session ends.
        /// </summary>
        /// <value>Date and optionally time when event session ends.</value>

        [DataMember(Name = "EndDate")]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// Indicates whether end time was explicitly specified in EndDate. A value of false means EndDate contains date only.
        /// </summary>
        /// <value>Indicates whether end time was explicitly specified in EndDate. A value of false means EndDate contains date only.</value>

        [DataMember(Name = "EndTimeSpecified")]
        public bool? EndTimeSpecified { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EventSession {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  StartTimeSpecified: ").Append(StartTimeSpecified).Append("\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("  EndTimeSpecified: ").Append(EndTimeSpecified).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((EventSession)obj);
        }

        /// <summary>
        /// Returns true if EventSession instances are equal
        /// </summary>
        /// <param name="other">Instance of EventSession to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventSession other)
        {
            if (ReferenceEquals(null, other))
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (Id == other.Id || Id != null && Id.Equals(other.Id))
                && (Title == other.Title || Title != null && Title.Equals(other.Title))
                && (
                    StartDate == other.StartDate
                    || StartDate != null && StartDate.Equals(other.StartDate)
                )
                && (
                    StartTimeSpecified == other.StartTimeSpecified
                    || StartTimeSpecified != null
                        && StartTimeSpecified.Equals(other.StartTimeSpecified)
                )
                && (EndDate == other.EndDate || EndDate != null && EndDate.Equals(other.EndDate))
                && (
                    EndTimeSpecified == other.EndTimeSpecified
                    || EndTimeSpecified != null && EndTimeSpecified.Equals(other.EndTimeSpecified)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                if (StartDate != null)
                    hashCode = hashCode * 59 + StartDate.GetHashCode();
                if (StartTimeSpecified != null)
                    hashCode = hashCode * 59 + StartTimeSpecified.GetHashCode();
                if (EndDate != null)
                    hashCode = hashCode * 59 + EndDate.GetHashCode();
                if (EndTimeSpecified != null)
                    hashCode = hashCode * 59 + EndTimeSpecified.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(EventSession left, EventSession right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EventSession left, EventSession right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
