/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// it describes reqired information for register in waitlist (Undefined value is unexpected)
    /// </summary>
    /// <value>it describes reqired information for register in waitlist (Undefined value is unexpected)</value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum EventWaitlistInformationToCollect
    {
        /// <summary>
        /// Enum UndefinedEnum for Undefined
        /// </summary>
        [EnumMember(Value = "Undefined")]
        UndefinedEnum = 0,

        /// <summary>
        /// Enum NameAndEmailEnum for NameAndEmail
        /// </summary>
        [EnumMember(Value = "NameAndEmail")]
        NameAndEmailEnum = 1,

        /// <summary>
        /// Enum ContactInformationEnum for ContactInformation
        /// </summary>
        [EnumMember(Value = "ContactInformation")]
        ContactInformationEnum = 2,

        /// <summary>
        /// Enum RegistrationInformationEnum for RegistrationInformation
        /// </summary>
        [EnumMember(Value = "RegistrationInformation")]
        RegistrationInformationEnum = 3,
    }
}
