/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Describes event registration status
    /// </summary>
    /// <value>Describes event registration status </value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum EventRegistrationStatus
    {
        /// <summary>
        /// Enum UndefinedEnum for Undefined
        /// </summary>
        [EnumMember(Value = "Undefined")]
        UndefinedEnum = 0,

        /// <summary>
        /// Enum PaidEnum for Paid
        /// </summary>
        [EnumMember(Value = "Paid")]
        PaidEnum = 1,

        /// <summary>
        /// Enum UnpaidEnum for Unpaid
        /// </summary>
        [EnumMember(Value = "Unpaid")]
        UnpaidEnum = 2,

        /// <summary>
        /// Enum PartiallyPaidEnum for PartiallyPaid
        /// </summary>
        [EnumMember(Value = "PartiallyPaid")]
        PartiallyPaidEnum = 3,

        /// <summary>
        /// Enum CanceledEnum for Canceled
        /// </summary>
        [EnumMember(Value = "Canceled")]
        CanceledEnum = 4,

        /// <summary>
        /// Enum FreeEnum for Free
        /// </summary>
        [EnumMember(Value = "Free")]
        FreeEnum = 5,

        /// <summary>
        /// Enum NoInvoiceEnum for NoInvoice
        /// </summary>
        [EnumMember(Value = "NoInvoice")]
        NoInvoiceEnum = 6,

        /// <summary>
        /// Enum OnWaitlistEnum for OnWaitlist
        /// </summary>
        [EnumMember(Value = "OnWaitlist")]
        OnWaitlistEnum = 7,
    }
}
