/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Indicates who can see event registrants.
    /// </summary>
    /// <value>Indicates who can see event registrants.</value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum EventRegistrationsPublicVisibility
    {
        /// <summary>
        /// Enum NobodyEnum for Nobody
        /// </summary>
        [EnumMember(Value = "Nobody")]
        NobodyEnum = 0,

        /// <summary>
        /// Enum MembersEnum for Members
        /// </summary>
        [EnumMember(Value = "Members")]
        MembersEnum = 1,

        /// <summary>
        /// Enum AnybodyEnum for Anybody
        /// </summary>
        [EnumMember(Value = "Anybody")]
        AnybodyEnum = 2,
    }
}
