/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Event cancellation behavior types.
    /// </summary>
    /// <value>Event cancellation behavior types.</value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum EventCancellationBehavior
    {
        /// <summary>
        /// Enum NoneEnum for None
        /// </summary>
        [EnumMember(Value = "None")]
        NoneEnum = 0,

        /// <summary>
        /// Enum DoNotAllowEnum for DoNotAllow
        /// </summary>
        [EnumMember(Value = "DoNotAllow")]
        DoNotAllowEnum = 1,

        /// <summary>
        /// Enum AllowUpToPeriodBeforeEventEnum for AllowUpToPeriodBeforeEvent
        /// </summary>
        [EnumMember(Value = "AllowUpToPeriodBeforeEvent")]
        AllowUpToPeriodBeforeEventEnum = 2,

        /// <summary>
        /// Enum AllowEnum for Allow
        /// </summary>
        [EnumMember(Value = "Allow")]
        AllowEnum = 3,
    }
}
