/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Contains a collection of attendees or number of attendees or list of of attendee identifiers, depending on passed query parameters.
    /// </summary>
    [DataContract]
    public partial class EventAttendeesResponse : IEquatable<EventAttendeesResponse>
    {
        /// <summary>
        /// List of public event registration infos found.
        /// </summary>
        /// <value>List of public event registration infos found.</value>

        [DataMember(Name = "RegistrationPublicInfos")]
        public List<EventRegistrationPublicInfo> RegistrationPublicInfos { get; set; }

        /// <summary>
        /// List of event registration IDs found.
        /// </summary>
        /// <value>List of event registration IDs found.</value>

        [DataMember(Name = "Identifiers")]
        public List<int?> Identifiers { get; set; }

        /// <summary>
        /// Number of registrations found. Value appears only if $count was passed in parameters.
        /// </summary>
        /// <value>Number of registrations found. Value appears only if $count was passed in parameters.</value>

        [DataMember(Name = "Count")]
        public int? Count { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EventAttendeesResponse {\n");
            sb.Append("  RegistrationPublicInfos: ").Append(RegistrationPublicInfos).Append("\n");
            sb.Append("  Identifiers: ").Append(Identifiers).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((EventAttendeesResponse)obj);
        }

        /// <summary>
        /// Returns true if EventAttendeesResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of EventAttendeesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventAttendeesResponse other)
        {
            if (ReferenceEquals(null, other))
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (
                    RegistrationPublicInfos == other.RegistrationPublicInfos
                    || RegistrationPublicInfos != null
                        && RegistrationPublicInfos.SequenceEqual(other.RegistrationPublicInfos)
                )
                && (
                    Identifiers == other.Identifiers
                    || Identifiers != null && Identifiers.SequenceEqual(other.Identifiers)
                )
                && (Count == other.Count || Count != null && Count.Equals(other.Count));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (RegistrationPublicInfos != null)
                    hashCode = hashCode * 59 + RegistrationPublicInfos.GetHashCode();
                if (Identifiers != null)
                    hashCode = hashCode * 59 + Identifiers.GetHashCode();
                if (Count != null)
                    hashCode = hashCode * 59 + Count.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(EventAttendeesResponse left, EventAttendeesResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EventAttendeesResponse left, EventAttendeesResponse right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
