/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Description of multiplier field.   ItemPrice multiplier specifies a price for each requested item.   Percentage multiplier specifies the percentage of the field value to use as extra charge.
    /// </summary>
    /// <value>Description of multiplier field.   ItemPrice multiplier specifies a price for each requested item.   Percentage multiplier specifies the percentage of the field value to use as extra charge. </value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum ExtraChargeMultiplierType
    {
        /// <summary>
        /// Enum ItemPriceEnum for ItemPrice
        /// </summary>
        [EnumMember(Value = "ItemPrice")]
        ItemPriceEnum = 0,

        /// <summary>
        /// Enum PercentageEnum for Percentage
        /// </summary>
        [EnumMember(Value = "Percentage")]
        PercentageEnum = 1,
    }
}
