/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Gets or Sets GuestRegistrationPolicy
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum GuestRegistrationPolicy
    {
        /// <summary>
        /// Enum DisabledEnum for Disabled
        /// </summary>
        [EnumMember(Value = "Disabled")]
        DisabledEnum = 0,

        /// <summary>
        /// Enum NumberOfGuestsEnum for NumberOfGuests
        /// </summary>
        [EnumMember(Value = "NumberOfGuests")]
        NumberOfGuestsEnum = 1,

        /// <summary>
        /// Enum CollectContactDetailsEnum for CollectContactDetails
        /// </summary>
        [EnumMember(Value = "CollectContactDetails")]
        CollectContactDetailsEnum = 2,

        /// <summary>
        /// Enum CollectFullInformationEnum for CollectFullInformation
        /// </summary>
        [EnumMember(Value = "CollectFullInformation")]
        CollectFullInformationEnum = 3,
    }
}
