/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// A reason for creating the invoice.
    /// </summary>
    /// <value>A reason for creating the invoice.</value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum InvoiceOrderType
    {
        /// <summary>
        /// Enum MembershipApplicationEnum for MembershipApplication
        /// </summary>
        [EnumMember(Value = "MembershipApplication")]
        MembershipApplicationEnum = 0,

        /// <summary>
        /// Enum MembershipRenewalEnum for MembershipRenewal
        /// </summary>
        [EnumMember(Value = "MembershipRenewal")]
        MembershipRenewalEnum = 1,

        /// <summary>
        /// Enum MembershipLevelChangeEnum for MembershipLevelChange
        /// </summary>
        [EnumMember(Value = "MembershipLevelChange")]
        MembershipLevelChangeEnum = 2,

        /// <summary>
        /// Enum EventRegistrationEnum for EventRegistration
        /// </summary>
        [EnumMember(Value = "EventRegistration")]
        EventRegistrationEnum = 3,

        /// <summary>
        /// Enum DonationEnum for Donation
        /// </summary>
        [EnumMember(Value = "Donation")]
        DonationEnum = 4,

        /// <summary>
        /// Enum OnlineStoreEnum for OnlineStore
        /// </summary>
        [EnumMember(Value = "OnlineStore")]
        OnlineStoreEnum = 5,
    }
}
