/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class Localization : IEquatable<Localization>
    {
        /// <summary>
        /// Format for displaying dates
        /// </summary>
        /// <value>Format for displaying dates</value>

        [DataMember(Name = "DateFormat")]
        public string DateFormat { get; set; }

        /// <summary>
        /// Format for displaying time
        /// </summary>
        /// <value>Format for displaying time</value>

        [DataMember(Name = "TimeFormat")]
        public string TimeFormat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Localization {\n");
            sb.Append("  DateFormat: ").Append(DateFormat).Append("\n");
            sb.Append("  TimeFormat: ").Append(TimeFormat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((Localization)obj);
        }

        /// <summary>
        /// Returns true if Localization instances are equal
        /// </summary>
        /// <param name="other">Instance of Localization to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Localization other)
        {
            if (ReferenceEquals(null, other))
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (
                    DateFormat == other.DateFormat
                    || DateFormat != null && DateFormat.Equals(other.DateFormat)
                )
                && (
                    TimeFormat == other.TimeFormat
                    || TimeFormat != null && TimeFormat.Equals(other.TimeFormat)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (DateFormat != null)
                    hashCode = hashCode * 59 + DateFormat.GetHashCode();
                if (TimeFormat != null)
                    hashCode = hashCode * 59 + TimeFormat.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(Localization left, Localization right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Localization left, Localization right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
