/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Gets or Sets MembershipLevelType
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum MembershipLevelType
    {
        /// <summary>
        /// Enum IndividualEnum for Individual
        /// </summary>
        [EnumMember(Value = "Individual")]
        IndividualEnum = 0,

        /// <summary>
        /// Enum BundleEnum for Bundle
        /// </summary>
        [EnumMember(Value = "Bundle")]
        BundleEnum = 1,
    }
}
