/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Type of invoice detail item.
    /// </summary>
    /// <value>Type of invoice detail item.</value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum OrderDetailType
    {
        /// <summary>
        /// Enum UnspecifiedEnum for Unspecified
        /// </summary>
        [EnumMember(Value = "Unspecified")]
        UnspecifiedEnum = 0,

        /// <summary>
        /// Enum EventRegistrationEnum for EventRegistration
        /// </summary>
        [EnumMember(Value = "EventRegistration")]
        EventRegistrationEnum = 1,

        /// <summary>
        /// Enum GuestsNumberEnum for GuestsNumber
        /// </summary>
        [EnumMember(Value = "GuestsNumber")]
        GuestsNumberEnum = 2,

        /// <summary>
        /// Enum GuestCardEnum for GuestCard
        /// </summary>
        [EnumMember(Value = "GuestCard")]
        GuestCardEnum = 3,

        /// <summary>
        /// Enum ExtraCostEnum for ExtraCost
        /// </summary>
        [EnumMember(Value = "ExtraCost")]
        ExtraCostEnum = 4,

        /// <summary>
        /// Enum MemberLevelEnum for MemberLevel
        /// </summary>
        [EnumMember(Value = "MemberLevel")]
        MemberLevelEnum = 5,

        /// <summary>
        /// Enum ProrateEnum for Prorate
        /// </summary>
        [EnumMember(Value = "Prorate")]
        ProrateEnum = 6,

        /// <summary>
        /// Enum DiscountEnum for Discount
        /// </summary>
        [EnumMember(Value = "Discount")]
        DiscountEnum = 7,

        /// <summary>
        /// Enum DonationEnum for Donation
        /// </summary>
        [EnumMember(Value = "Donation")]
        DonationEnum = 8,

        /// <summary>
        /// Enum OnlineStoreProductEnum for OnlineStoreProduct
        /// </summary>
        [EnumMember(Value = "OnlineStoreProduct")]
        OnlineStoreProductEnum = 9,

        /// <summary>
        /// Enum OnlineStoreShippingEnum for OnlineStoreShipping
        /// </summary>
        [EnumMember(Value = "OnlineStoreShipping")]
        OnlineStoreShippingEnum = 10,
    }
}
