/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Current status of payment started with startPayment api call
    /// </summary>
    /// <value>Current status of payment started with startPayment api call</value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum PaymentStatus
    {
        /// <summary>
        /// Enum OKEnum for OK
        /// </summary>
        [EnumMember(Value = "OK")]
        OKEnum = 0,

        /// <summary>
        /// Enum FailedEnum for Failed
        /// </summary>
        [EnumMember(Value = "Failed")]
        FailedEnum = 1,

        /// <summary>
        /// Enum InProgressEnum for InProgress
        /// </summary>
        [EnumMember(Value = "InProgress")]
        InProgressEnum = 2,

        /// <summary>
        /// Enum CancelledEnum for Cancelled
        /// </summary>
        [EnumMember(Value = "Cancelled")]
        CancelledEnum = 3,
    }
}
