/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Whether this registration type is available for Everyone or just MembersOnly.
    /// </summary>
    /// <value>Whether this registration type is available for Everyone or just MembersOnly.</value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum RegistrationTypeAccessLevel
    {
        /// <summary>
        /// Enum EveryoneEnum for Everyone
        /// </summary>
        [EnumMember(Value = "Everyone")]
        EveryoneEnum = 0,

        /// <summary>
        /// Enum MembersOnlyEnum for MembersOnly
        /// </summary>
        [EnumMember(Value = "MembersOnly")]
        MembersOnlyEnum = 1,
    }
}
