/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// How often membership should be renewed
    /// </summary>
    /// <value>How often membership should be renewed</value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum RenewalPeriodKind
    {
        /// <summary>
        /// Enum NeverEnum for Never
        /// </summary>
        [EnumMember(Value = "Never")]
        NeverEnum = 0,

        /// <summary>
        /// Enum MonthlyEnum for Monthly
        /// </summary>
        [EnumMember(Value = "Monthly")]
        MonthlyEnum = 1,

        /// <summary>
        /// Enum QuarterlyEnum for Quarterly
        /// </summary>
        [EnumMember(Value = "Quarterly")]
        QuarterlyEnum = 2,

        /// <summary>
        /// Enum TwiceAYearEnum for TwiceAYear
        /// </summary>
        [EnumMember(Value = "TwiceAYear")]
        TwiceAYearEnum = 3,

        /// <summary>
        /// Enum EveryNYearsEnum for EveryNYears
        /// </summary>
        [EnumMember(Value = "EveryNYears")]
        EveryNYearsEnum = 4,
    }
}
