/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class RenewalLimits : IEquatable<RenewalLimits>
    {
        /// <summary>
        /// Limit renewal to 1 period ahead
        /// </summary>
        /// <value>Limit renewal to 1 period ahead</value>

        [DataMember(Name = "OnePeriodAhead")]
        public bool? OnePeriodAhead { get; set; }

        /// <summary>
        /// Gets or Sets ExpirationPeriod
        /// </summary>

        [DataMember(Name = "ExpirationPeriod")]
        public RenewalExpirationPeriod ExpirationPeriod { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RenewalLimits {\n");
            sb.Append("  OnePeriodAhead: ").Append(OnePeriodAhead).Append("\n");
            sb.Append("  ExpirationPeriod: ").Append(ExpirationPeriod).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((RenewalLimits)obj);
        }

        /// <summary>
        /// Returns true if RenewalLimits instances are equal
        /// </summary>
        /// <param name="other">Instance of RenewalLimits to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RenewalLimits other)
        {
            if (ReferenceEquals(null, other))
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (
                    OnePeriodAhead == other.OnePeriodAhead
                    || OnePeriodAhead != null && OnePeriodAhead.Equals(other.OnePeriodAhead)
                )
                && (
                    ExpirationPeriod == other.ExpirationPeriod
                    || ExpirationPeriod != null && ExpirationPeriod.Equals(other.ExpirationPeriod)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (OnePeriodAhead != null)
                    hashCode = hashCode * 59 + OnePeriodAhead.GetHashCode();
                if (ExpirationPeriod != null)
                    hashCode = hashCode * 59 + ExpirationPeriod.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(RenewalLimits left, RenewalLimits right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RenewalLimits left, RenewalLimits right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
