/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class RenewalExpirationPeriod : IEquatable<RenewalExpirationPeriod>
    {
        /// <summary>
        /// Limit renewal to within certain period
        /// </summary>
        /// <value>Limit renewal to within certain period</value>

        [DataMember(Name = "Active")]
        public bool? Active { get; set; }

        /// <summary>
        /// number of Days or Weeks (PeriodType)
        /// </summary>
        /// <value>number of Days or Weeks (PeriodType)</value>

        [DataMember(Name = "Length")]
        public int? Length { get; set; }

        /// <summary>
        /// Gets or Sets PeriodType
        /// </summary>

        [DataMember(Name = "PeriodType")]
        public RenewalExpirationPeriodType PeriodType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RenewalExpirationPeriod {\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  PeriodType: ").Append(PeriodType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((RenewalExpirationPeriod)obj);
        }

        /// <summary>
        /// Returns true if RenewalExpirationPeriod instances are equal
        /// </summary>
        /// <param name="other">Instance of RenewalExpirationPeriod to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RenewalExpirationPeriod other)
        {
            if (ReferenceEquals(null, other))
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (Active == other.Active || Active != null && Active.Equals(other.Active))
                && (Length == other.Length || Length != null && Length.Equals(other.Length))
                && (
                    PeriodType == other.PeriodType
                    || PeriodType != null && PeriodType.Equals(other.PeriodType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Active != null)
                    hashCode = hashCode * 59 + Active.GetHashCode();
                if (Length != null)
                    hashCode = hashCode * 59 + Length.GetHashCode();
                if (PeriodType != null)
                    hashCode = hashCode * 59 + PeriodType.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(RenewalExpirationPeriod left, RenewalExpirationPeriod right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RenewalExpirationPeriod left, RenewalExpirationPeriod right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
