/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Expiration period type
    /// </summary>
    /// <value>Expiration period type</value>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum RenewalExpirationPeriodType
    {
        /// <summary>
        /// Enum DaysEnum for Days
        /// </summary>
        [EnumMember(Value = "Days")]
        DaysEnum = 0,

        /// <summary>
        /// Enum MonthsEnum for Months
        /// </summary>
        [EnumMember(Value = "Months")]
        MonthsEnum = 1,
    }
}
