/*
 * Wild Apricot API for non-administrative access
 *
 * Wild Apricot API for non-administrative access
 *
 * OpenAPI spec version: 8.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace WildApricot.Models
{
    /// <summary>
    /// Taxes applied to the invoice according to account Tax Rules settings.
    /// </summary>
    [DataContract]
    public partial class SalesTax : IEquatable<SalesTax>
    {
        /// <summary>
        /// Internal account tax name.
        /// </summary>
        /// <value>Internal account tax name.</value>

        [DataMember(Name = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Public tax ID (displayed on invoices).
        /// </summary>
        /// <value>Public tax ID (displayed on invoices).</value>

        [DataMember(Name = "PublicId")]
        public string PublicId { get; set; }

        /// <summary>
        /// Tax rate value.
        /// </summary>
        /// <value>Tax rate value.</value>

        [DataMember(Name = "Rate")]
        public decimal? Rate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SalesTax {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PublicId: ").Append(PublicId).Append("\n");
            sb.Append("  Rate: ").Append(Rate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            return obj.GetType() == GetType() && Equals((SalesTax)obj);
        }

        /// <summary>
        /// Returns true if SalesTax instances are equal
        /// </summary>
        /// <param name="other">Instance of SalesTax to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SalesTax other)
        {
            if (ReferenceEquals(null, other))
                return false;
            if (ReferenceEquals(this, other))
                return true;

            return (Name == other.Name || Name != null && Name.Equals(other.Name))
                && (
                    PublicId == other.PublicId
                    || PublicId != null && PublicId.Equals(other.PublicId)
                )
                && (Rate == other.Rate || Rate != null && Rate.Equals(other.Rate));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (PublicId != null)
                    hashCode = hashCode * 59 + PublicId.GetHashCode();
                if (Rate != null)
                    hashCode = hashCode * 59 + Rate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SalesTax left, SalesTax right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SalesTax left, SalesTax right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
